**Bibliografía:**
Practical Convolutional Neural Networks: Implement advanced deep learning models using Python

**Building blocks of a neural network**

Una red neuronal está formada por muchas neuronas artificiales. ¿Es una representación del cerebro o es una representación matemática de algún conocimiento? Aquí, simplemente intentaremos comprender cómo se usa una red neuronal en la práctica. Una red neuronal convolucional (CNN) es un tipo muy especial de red neuronal multicapa. CNN está diseñado para reconocer patrones visuales directamente a partir de imágenes con un procesamiento mínimo.

Una neurona artificial es una función que toma una entrada y produce una salida. La cantidad de neuronas que se utilizan depende de la tarea en cuestión. Podría ser tan bajo como dos o hasta varios miles. Existen numerosas formas de conectar neuronas artificiales para crear una CNN. Una de esas topologías que se usa comúnmente se conoce como red de alimentación directa:

![](neurona_pesos.png)

Cada neurona recibe información de otras neuronas. El efecto de cada línea de entrada en la neurona está controlado por el peso. El peso puede ser positivo o negativo. Toda la red neuronal aprende a realizar cálculos útiles para reconocer objetos mediante la comprensión del lenguaje. Ahora, podemos conectar esas neuronas en una red conocida como red de avance. Esto significa que las neuronas en cada capa alimentan su salida hacia la siguiente capa hasta que obtenemos una salida final.

La neurona de propagación directa anterior se puede implementar de la siguiente manera:

In [26]:
import numpy as np
import math

In [27]:
class Neuron(object):
    def __init__(self):
        self.weights = np.array([1.0, 2.0])
        self.bias = 0.0
    def forward(self, inputs):
        """ Assuming that inputs and weights are 1-D numpy arrays and the bias is
a number """
        a_cell_sum = np.sum(inputs * self.weights) + self.bias
        result = 1.0 / (1.0 + math.exp(-a_cell_sum)) # This is the sigmoid activation function
        return result

In [28]:
neuron = Neuron()
output = neuron.forward(np.array([1,1]))
print(output)

0.9525741268224334


Como se puede ver se tiene una clase de nombre *Neuron* la cual crea una neurona con un bias de 0.0 y un determinado arreglo np de pesos.
Luego la función *forward* se encarga de "ingresalre" a la nuerona inputs para obtener un resultado, habiendole aplicado anteriormente la función de activación (En este caso una sigmoide).

b'Hello World!'


**Introduction to TensorFlow**

TensorFlow se basa en cálculos basados en gráficos. Considere la siguiente expresión matemática, por ejemplo:

c = (a + b), d = b + 5,
e = c * d

En TensorFlow, esto se representa como un gráfico computacional, como se muestra aquí. Esto es poderoso porque los cálculos se realizan en paralelo:

![](tensorflow_graph.png)

**TensorFlow basics**

En TensorFlow, los datos no se almacenan como números enteros, flotantes, cadenas u otras primitivas. Estos valores están encapsulados en un objeto llamado tensor. Consiste en un conjunto de valores primitivos conformados en una matriz de cualquier número de dimensiones. El número de dimensiones en un tensor se llama rango. Algunos ejemplos más de tensores constantes son los siguientes:

In [29]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 

In [30]:
# A is an int32 tensor with rank = 0
A = tf.constant(123)
# B is an int32 tensor with dimension of 1 ( rank = 1 )
B = tf.constant([123,456,789])
# C is an int32 2- dimensional tensor
C = tf.constant([ [123,456,789], [222,333,444] ])

In [31]:
#Creating TensorFlow object
hello_constant = tf.constant('Hello World!', name = 'hello_constant')
#Creating a session object for execution of the computational graph
with tf.Session() as sess:
    #Implementing the tf.constant operation in the session
    output = sess.run(hello_constant)
    print(output)

b'Hello World!'


El programa principal de TensorFlow se basa en la idea de un gráfico computacional. Un gráfico computacional es un gráfico dirigido que consta de las dos partes siguientes:
- Construyendo un gráfico computacional
- Ejecutando un gráfico computacional

Un gráfico computacional se ejecuta dentro de una sesión. Una sesión de TensorFlow es un entorno de ejecución para el gráfico computacional. Asigna la CPU o GPU y mantiene el estado del tiempo de ejecución de TensorFlow. El siguiente código crea una instancia de sesión llamada sess usando tf.Session. Luego, la función sess.run () evalúa el tensor y devuelve los resultados almacenados en la variable de salida. ¡Finalmente se imprime como Hello World !:

In [32]:
with tf.Session() as sess:
    # Run the tf.constant operation in the session
    output = sess.run(hello_constant)
    print(output)

b'Hello World!'


In [11]:
## tensorboard --logdir=path/to/log-directory

**Basic math with TensorFlow**

- La función tf.add () toma dos números, dos tensores o uno de cada uno, y devuelve su suma como un tensor:

In [33]:
## Addition
x = tf.add(1, 2, name=None) # 3
print (x)

Tensor("Add_2:0", shape=(), dtype=int32)


In [35]:
## Here's an example with subtraction and multiplication:
x = tf.subtract(1, 2,name=None) # -1
y = tf.multiply(2, 5,name=None) # 10

print (x)
print (y)

Tensor("Sub_3:0", shape=(), dtype=int32)
Tensor("Mul_4:0", shape=(), dtype=int32)


http://blog.crespo.org.ve/2018/02/hola-mundo-desde-tensorflow.html

In [36]:
#Se crea una constante en la variable hola, donde se le pasa un string
hola = tf.constant("Hola mundo desde TensorFlow!")

In [37]:
#Veamos que devuelve la variable hola
print(hola)

Tensor("Const_7:0", shape=(), dtype=string)


In [38]:
#Se crea la sesión de tensorflow
sess=tf.Session()

In [39]:
#Se corre la sesión pasandole la variable hola
print(sess.run(hola))

b'Hola mundo desde TensorFlow!'


Como se puede ver, para poder visualizar el valor de una constante de TensorFlow se 
tiene que crear la sesión y ejecutar en la sesión la constante.

¿Qué pasa si queremos usar una no constante? ¿Cómo alimentar un conjunto de datos de entrada a TensorFlow? Para esto, TensorFlow proporciona una API, tf.placeholder (), y usa feed_dict.

Un marcador de posición es una variable a la que se asignan datos más adelante en la función tf.session.run (). Con la ayuda de esto, se pueden crear nuestras operaciones y podemos construir nuestro gráfico computacional sin necesidad de los datos. Posteriormente, estos datos se introducen en el gráfico a través de estos marcadores de posición con la ayuda del parámetro feed_dict en tf.session.run () para establecer el tensor del marcador de posición. En el siguiente ejemplo, el tensor x se establece en la cadena Hello World antes de que se ejecute la sesión:

In [40]:
x = tf.placeholder(tf.string)
with tf.Session() as sess:
    output = sess.run(x, feed_dict={x: 'Hello World'})

print (x)
output

Tensor("Placeholder_5:0", dtype=string)


array('Hello World', dtype=object)

El objeto Variable de Tensorflow permite definir una variable (almacenar un estado en un objeto Graph con un valor inicial), en cambio, el objeto placeholder se usa para agregar datos externos dentro de un Objeto Graph, pero los datos a agregar no se agregan al crear el placeholder, para ello se usa la inicialización de las variables.

También es posible establecer más de un tensor usando feed_dict, de la siguiente manera:

In [41]:
x = tf.placeholder(tf.string)
y = tf.placeholder(tf.int32, None)
z = tf.placeholder(tf.float32, None)
with tf.Session() as sess:
    output = sess.run(x, feed_dict={x: 'Welcome to CNN', y: 123, z: 123.45})

output

array('Welcome to CNN', dtype=object)

Los marcadores de posición también pueden permitir el almacenamiento de matrices con la ayuda de múltiples dimensiones. Por favor, vea el siguiente ejemplo:

In [42]:
x = tf.placeholder("float", [None, 3])
y = x * 2
with tf.Session() as session:
    input_data = [[1, 2, 3],
                [4, 5, 6],]
    result = session.run(y, feed_dict={x: input_data})
    print(result)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]


**La función tf.truncated_normal () devuelve un tensor con valores aleatorios de una distribución normal. Esto se usa principalmente para la inicialización del peso en una red:**

In [43]:
n_features = 5
n_labels = 2
weights = tf.truncated_normal((n_features, n_labels))
with tf.Session() as sess:
    print(sess.run(weights))

[[ 0.8804754   0.13455978]
 [ 0.07356802 -1.1384797 ]
 [ 0.29588625 -0.1706254 ]
 [-0.9211794   1.5955393 ]
 [ 0.2450367  -1.036288  ]]
